package UserExpense;

import loginandregister.Login;

public class UserExpense extends javax.swing.JFrame {

    private int currentUserId;

    public UserExpense(String loggedInUsername, int loggedInUserId) {
        initComponents();
        this.currentUserId = loggedInUserId;

        if (welcomeText != null) {
            welcomeText.setText("Welcome, " + loggedInUsername);
        }

        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < expenseTable.getColumnCount(); i++) {
            expenseTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        expenseTable.getColumnModel().getColumn(4).setMinWidth(0);
        expenseTable.getColumnModel().getColumn(4).setMaxWidth(0);
        expenseTable.getColumnModel().getColumn(4).setPreferredWidth(0);

        expenseTable.setShowGrid(true);
        expenseTable.setShowHorizontalLines(true);
        expenseTable.setShowVerticalLines(true);
        expenseTable.setGridColor(new java.awt.Color(200, 200, 200));
        expenseTable.setRowHeight(30);

        loadExpensesFromDatabase();
    }

    private void loadExpensesFromDatabase() {
        Backend.ExpenseManager manager = new Backend.ExpenseManager();
        java.util.List<Backend.Expense> list = manager.getExpensesByUser(this.currentUserId);

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) expenseTable.getModel();
        model.setRowCount(0);

        for (Backend.Expense e : list) {
            model.addRow(new Object[]{
                e.getCategoryName(),
                e.getDescription(),
                String.format("%.2f", e.getAmount()),
                e.getExpenseDate(),
                e.getExpenseId()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        UsernameMenu = new javax.swing.JPopupMenu();
        Logout = new javax.swing.JMenuItem();
        MainPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JPanel();
        ToolbarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        summaryButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        expenseTable = new javax.swing.JTable();

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        UsernameMenu.add(Logout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(254, 249, 231));
        MainPanel.setLayout(new java.awt.BorderLayout());

        HeaderPanel.setBackground(new java.awt.Color(30, 41, 59));
        HeaderPanel.setMinimumSize(new java.awt.Dimension(87, 50));
        HeaderPanel.setLayout(new java.awt.BorderLayout());

        welcomeText.setBackground(new java.awt.Color(254, 249, 231));
        welcomeText.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(254, 249, 231));
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        welcomeText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AccountIcon.png"))); // NOI18N
        welcomeText.setText("Welcome User!");
        welcomeText.setPreferredSize(new java.awt.Dimension(87, 50));
        welcomeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                welcomeTextMouseClicked(evt);
            }
        });
        HeaderPanel.add(welcomeText, java.awt.BorderLayout.PAGE_START);

        Title.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(254, 249, 231));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Expense Tracker");
        Title.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        HeaderPanel.add(Title, java.awt.BorderLayout.CENTER);

        MainPanel.add(HeaderPanel, java.awt.BorderLayout.NORTH);

        ContentPanel.setBackground(new java.awt.Color(254, 249, 231));
        ContentPanel.setLayout(new java.awt.BorderLayout());

        ToolbarPanel.setBackground(new java.awt.Color(254, 249, 231));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 41, 59));
        jLabel1.setText("Expenses");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(100.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setIconTextGap(100);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        ToolbarPanel.add(jLabel1);

        addButton.setBackground(new java.awt.Color(30, 41, 59));
        addButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(254, 249, 231));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(addButton);

        editButton.setBackground(new java.awt.Color(30, 41, 59));
        editButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(254, 249, 231));
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(editButton);

        deleteButton.setBackground(new java.awt.Color(30, 41, 59));
        deleteButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(254, 249, 231));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(deleteButton);

        summaryButton.setBackground(new java.awt.Color(30, 41, 59));
        summaryButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        summaryButton.setForeground(new java.awt.Color(254, 249, 231));
        summaryButton.setText("SUMMARY");
        summaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryButtonActionPerformed(evt);
            }
        });
        ToolbarPanel.add(summaryButton);

        ContentPanel.add(ToolbarPanel, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(254, 249, 231));
        jScrollPane1.setForeground(new java.awt.Color(30, 41, 59));
        jScrollPane1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N

        expenseTable.setBackground(new java.awt.Color(254, 249, 231));
        expenseTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        expenseTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        expenseTable.setForeground(new java.awt.Color(30, 41, 59));
       expenseTable.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {},
    new String [] {
        "Category", "Description", "Amount", "Date", "ID" 
    }
) {
    Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Integer.class
    };
    boolean[] canEdit = new boolean [] {
        false, false, false, false, false
    };

    public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
    }

    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
    }
});
        expenseTable.setFillsViewportHeight(true);
        expenseTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(expenseTable);

        ContentPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        MainPanel.add(ContentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.setVisible(false);
        this.dispose();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login logout = new Login();
                logout.pack();
                logout.setLocationRelativeTo(null);
                logout.setVisible(true);
            }
        });
    }//GEN-LAST:event_LogoutActionPerformed

    private void welcomeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeTextMouseClicked
        UsernameMenu.show(evt.getComponent(), 0, evt.getComponent().getHeight());
    }//GEN-LAST:event_welcomeTextMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddExpenseDialog dialog = new AddExpenseDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        if (dialog.isSaved) {
            Backend.Expense newExpense = new Backend.Expense(
                    this.currentUserId,
                    dialog.category,
                    dialog.amount,
                    dialog.description,
                    new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date())
            );

            Backend.ExpenseManager manager = new Backend.ExpenseManager();
            int databaseId = manager.addExpenseAndGetId(newExpense);

            if (databaseId != -1) {
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) expenseTable.getModel();
                model.addRow(new Object[]{
                    dialog.category,
                    dialog.description,
                    String.format("%.2f", dialog.amount),
                    newExpense.getExpenseDate(),
                    databaseId
                });
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to write record to the database.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) expenseTable.getModel();
        int selectedRow = expenseTable.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an item from the table to edit.", "Edit Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String currentCategory = model.getValueAt(selectedRow, 0).toString();
        String currentDescription = model.getValueAt(selectedRow, 1).toString();
        double currentAmount = Double.parseDouble(model.getValueAt(selectedRow, 2).toString());

        int currentId = Integer.parseInt(model.getValueAt(selectedRow, 4).toString());
        int activeUserId = this.currentUserId;

        EditExpenseDialog dialog = new EditExpenseDialog(this, true);
        dialog.setExpenseData(currentId, activeUserId, currentCategory, currentDescription, currentAmount);

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        if (dialog.isSaved) {
            model.setValueAt(dialog.category, selectedRow, 0);
            model.setValueAt(dialog.description, selectedRow, 1);
            model.setValueAt(String.format("%.2f", dialog.amount), selectedRow, 2);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) expenseTable.getModel();
        int selectedRow = expenseTable.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an item from the table to delete.", "Delete Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int currentId = Integer.parseInt(model.getValueAt(selectedRow, 4).toString());
        int activeUserId = this.currentUserId;

        int confirmation = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this expense permanently?",
                "Confirm Deletion",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
            Backend.ExpenseManager expenseManager = new Backend.ExpenseManager();
            boolean success = expenseManager.deleteExpense(currentId, activeUserId);

            if (success) {
                model.removeRow(selectedRow);
                javax.swing.JOptionPane.showMessageDialog(this, "Expense permanently deleted.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Database execution error: Failed to delete record.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void summaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryButtonActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) expenseTable.getModel();

        if (model.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "There are no expenses recorded.", "Summary Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Backend.ExpenseManager manager = new Backend.ExpenseManager();
        double grandTotal = manager.getTotalExpenses(this.currentUserId);
        double todaysExpenses = 0.0;

        String todayStr = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 2) != null && model.getValueAt(i, 3) != null) {
                try {
                    double amount = Double.parseDouble(model.getValueAt(i, 2).toString());
                    String entryDate = model.getValueAt(i, 3).toString();
                    if (entryDate.equals(todayStr)) {
                        todaysExpenses += amount;
                    }
                } catch (NumberFormatException e) {
                    System.out.println("Skipping invalid row layout format.");
                }
            }
        }

        SummaryDialog summary = new SummaryDialog(this, true);
        summary.setDisplayTotals(grandTotal, todaysExpenses);

        summary.setLocationRelativeTo(this);
        summary.setVisible(true);
    }//GEN-LAST:event_summaryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserExpense("Guest", 1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel ToolbarPanel;
    private javax.swing.JPopupMenu UsernameMenu;
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTable expenseTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton summaryButton;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
